name: CI-Somativa

on:
    push:
        branches: [ 'master' ]
    pull_request:
        branches: [ 'master' ]

    workflow_dispatch:

jobs:
    build-job:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - run: python3 -v

    teste-job:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - run: python3 helloworld.py

    deploy-job:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - run: echo 'Finalizado!'